version: "3"
services: 
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    # ports:
    #   - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  contracts:
    container_name: contracts-api
    hostname: contracts
    build: ./packages/contracts
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092

  billing:
    container_name: billing-api
    hostname: billing
    build: ./packages/billing
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092

  gateway:
    container_name: gateway-api
    hostname: gateway
    build: ./packages/gateway
    ports: 
      - "80:3002"
    depends_on:
      - contracts
      - billing
    environment:
      - CONTRACTS_URL=http://contracts:3000/
      - BILLING_URL=http://billing:3001/