version: "3"
services: 
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: wurstmeister/kafka
    expose:
      - "9093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093 #,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093 #,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

  contracts:
    container_name: contracts-api
    hostname: contracts
    build: 
      context: .
      dockerfile: contracts.Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9093
    expose:
      - "3000"
    networks:
      - backend

  billing:
    container_name: billing-api
    hostname: billing
    build: 
      context: .
      dockerfile: billing.Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9093
    expose:
      - "3001"
    networks:
      - backend

  gateway:
    container_name: gateway-api
    hostname: gateway
    build: 
      context: .
      dockerfile: gateway.Dockerfile
    ports: 
      - "8000:3002"
    environment:
      - CONTRACTS_URL=http://contracts:3000/
      - BILLING_URL=http://billing:3001/
    networks:
      - backend

networks:
  backend:
    driver: bridge
